parameters:
#    ultimate_site.example.class: Ultimate\SiteBundle\Example

services:
#    ultimate_site.example:
#        class: %ultimate_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
